 name: Node.js CI

 on:
   push:
     tags:
       - '*'

 jobs:
   build:
     runs-on: ubuntu-latest
    
     strategy:
       matrix:
         node-version: [10.x]

     steps:
     - uses: actions/checkout@v2
     - name: Use Node.js ${{ matrix.node-version }}
       uses: actions/setup-node@v1
       with:
         node-version: ${{ matrix.node-version }}
    
     - name: Running changelog generator
       env:
         GREN_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
       run: |
         npm install github-release-notes -g
         gren release --override
         gren changelog --override

     - name: Commiting CHANGELOG.md
       run: |
         git config --local user.name "charlescd"
         git add CHANGELOG.md
         git commit -m "Updating CHANGELOG.md"

     - name: Pushing changes
       uses: ad-m/github-push-action@master
       with:
         github_token: ${{ secrets.GITHUB_TOKEN }}
         force: true

